-- Seed 100+ AI tools for the Developer role
-- First, insert new tools that don't already exist, then link them to the Developer role

-- ============================================================
-- STEP 1: Insert new tools (ON CONFLICT DO NOTHING to skip existing)
-- ============================================================

INSERT INTO public.tools (name, slug, tagline, description, website_url, pricing_model, category_id, is_verified, is_trending) VALUES
-- Code & Development tools
('Devin', 'devin', 'The first AI software engineer', 'Autonomous AI software engineer that can plan, code, debug, and deploy entire projects end-to-end.', 'https://devin.ai', 'paid', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Sourcegraph Cody', 'sourcegraph-cody', 'AI coding assistant with full codebase context', 'AI coding assistant that understands your entire codebase and can answer questions, write code, and fix bugs.', 'https://sourcegraph.com/cody', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Amazon CodeWhisperer', 'amazon-codewhisperer', 'AI code companion from AWS', 'AI-powered code suggestions trained on billions of lines of code, integrated with AWS services.', 'https://aws.amazon.com/codewhisperer', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Pieces for Developers', 'pieces', 'AI-powered developer productivity', 'Saves, enriches, and reuses code snippets with AI, integrating across your entire workflow.', 'https://pieces.app', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('AskCodi', 'askcodi', 'AI coding assistant for all languages', 'AI-powered coding assistant that helps with code generation, documentation, and testing across multiple languages.', 'https://askcodi.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Blackbox AI', 'blackbox-ai', 'AI code generation and search', 'AI-powered code generation, code search, and code chat that helps developers write code faster.', 'https://blackbox.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Codiga', 'codiga', 'AI code analysis and suggestions', 'Static code analysis tool that uses AI to detect bugs, security vulnerabilities, and code quality issues.', 'https://codiga.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Mutable AI', 'mutable-ai', 'AI accelerated software development', 'AI-powered tool for auto-completing code, refactoring, and generating documentation from code.', 'https://mutable.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Mintlify', 'mintlify', 'AI-powered documentation', 'Automatically generates beautiful documentation from your code with AI-powered search and insights.', 'https://mintlify.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Sweep AI', 'sweep-ai', 'AI-powered junior developer', 'AI tool that turns GitHub issues into pull requests, handling bug fixes and small features autonomously.', 'https://sweep.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, true),
('Aider', 'aider', 'AI pair programming in your terminal', 'Command-line AI pair programming tool that edits code in your local git repo.', 'https://aider.chat', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Continue', 'continue-dev', 'Open-source AI code assistant', 'Open-source autopilot for VS Code and JetBrains that connects any LLM to your IDE.', 'https://continue.dev', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Supermaven', 'supermaven', 'Fastest AI code completion', 'Ultra-fast AI code completion with 1M token context window for understanding large codebases.', 'https://supermaven.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Codium AI', 'codium-ai', 'AI test generation', 'AI tool that analyzes your code and generates meaningful tests to catch bugs before they reach production.', 'https://codium.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Snyk', 'snyk', 'AI-powered security scanning', 'Developer-first security platform that uses AI to find and fix vulnerabilities in code, dependencies, and containers.', 'https://snyk.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('SonarQube', 'sonarqube', 'AI code quality analysis', 'Continuous code quality and security analysis with AI-powered suggestions for cleaner, safer code.', 'https://sonarqube.org', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Qodo (formerly CodiumAI)', 'qodo', 'AI code integrity platform', 'AI-powered platform for code review, test generation, and maintaining code quality standards.', 'https://qodo.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Vercel', 'vercel', 'AI-powered deployment platform', 'Frontend cloud platform with AI-powered features for building, deploying, and scaling web applications.', 'https://vercel.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Railway', 'railway', 'AI-assisted infrastructure', 'Modern infrastructure platform with AI-powered deployment, scaling, and monitoring for web apps.', 'https://railway.app', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Render', 'render', 'Cloud platform with AI features', 'Unified cloud platform to build and run apps with AI-assisted configuration and deployment.', 'https://render.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Hugging Face', 'hugging-face', 'The AI community platform', 'Open platform for sharing and deploying ML models, datasets, and AI applications.', 'https://huggingface.co', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('LangChain', 'langchain', 'Framework for LLM applications', 'Framework for developing applications powered by language models with chaining, agents, and memory.', 'https://langchain.com', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Ollama', 'ollama', 'Run LLMs locally', 'Run large language models locally on your machine with a simple command-line interface.', 'https://ollama.com', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('LM Studio', 'lm-studio', 'Desktop app for local LLMs', 'Discover, download, and run local LLMs with a user-friendly desktop application.', 'https://lmstudio.ai', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Phind', 'phind', 'AI search engine for developers', 'AI-powered search engine designed specifically for developers to find code solutions quickly.', 'https://phind.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Warp', 'warp', 'AI-powered terminal', 'Modern terminal with AI-powered command suggestions, natural language commands, and intelligent autocomplete.', 'https://warp.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Fig (now Amazon Q)', 'fig', 'AI terminal autocomplete', 'AI-powered autocomplete for your terminal with IDE-style suggestions and natural language commands.', 'https://fig.io', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('GitLab Duo', 'gitlab-duo', 'AI across the DevSecOps lifecycle', 'AI-powered features across the entire software development lifecycle within GitLab.', 'https://about.gitlab.com/gitlab-duo', 'paid', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('JetBrains AI', 'jetbrains-ai', 'AI assistant for JetBrains IDEs', 'AI-powered coding assistant integrated directly into IntelliJ IDEA, PyCharm, and other JetBrains IDEs.', 'https://jetbrains.com/ai', 'paid', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Cline', 'cline', 'Autonomous AI coding agent', 'AI coding agent for VS Code that can create files, run commands, and use the browser autonomously.', 'https://github.com/cline/cline', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('OpenHands', 'openhands', 'Open-source AI software developer', 'Open-source platform for AI-powered software development agents that can write, test, and debug code.', 'https://all-hands.dev', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, true),
('Lovable', 'lovable', 'AI full-stack app builder', 'Build full-stack web applications from natural language descriptions with AI.', 'https://lovable.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Dify', 'dify', 'Open-source LLM app platform', 'Open-source platform for building AI applications with visual workflows, RAG, and agent capabilities.', 'https://dify.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('n8n', 'n8n', 'AI workflow automation', 'Open-source workflow automation tool with AI nodes for building intelligent automation pipelines.', 'https://n8n.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Retool', 'retool', 'AI-powered internal tools', 'Build internal tools quickly with AI-assisted development, drag-and-drop UI, and database integrations.', 'https://retool.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Supabase', 'supabase', 'Open-source Firebase alternative', 'Open-source backend-as-a-service with AI-powered features including vector embeddings and edge functions.', 'https://supabase.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('PlanetScale', 'planetscale', 'AI-enhanced serverless MySQL', 'Serverless MySQL platform with AI-powered query insights and schema management.', 'https://planetscale.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Neon', 'neon', 'Serverless Postgres with AI', 'Serverless Postgres with AI-powered features including pgvector for embeddings and branching.', 'https://neon.tech', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Pinecone', 'pinecone', 'Vector database for AI', 'Purpose-built vector database for building high-performance AI applications with semantic search.', 'https://pinecone.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Weaviate', 'weaviate', 'Open-source vector database', 'Open-source vector database for AI-native applications with built-in ML models and hybrid search.', 'https://weaviate.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('ChromaDB', 'chromadb', 'Open-source embedding database', 'Open-source embedding database for building AI applications with semantic search and retrieval.', 'https://trychroma.com', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Sentry', 'sentry', 'AI-powered error tracking', 'Application monitoring platform with AI-powered error grouping, root cause analysis, and fix suggestions.', 'https://sentry.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Datadog', 'datadog', 'AI-powered observability', 'Cloud monitoring platform with AI-powered anomaly detection, log analysis, and incident management.', 'https://datadoghq.com', 'paid', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('PostHog', 'posthog', 'AI product analytics', 'Open-source product analytics with AI-powered insights, session replays, and feature flags.', 'https://posthog.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Raycast', 'raycast', 'AI-powered productivity launcher', 'Blazing fast productivity tool with built-in AI commands, snippets, and developer workflow extensions.', 'https://raycast.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Docker AI', 'docker-ai', 'AI-assisted containerization', 'AI-powered Docker tools for generating Dockerfiles, debugging containers, and optimizing images.', 'https://docker.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Terraform AI', 'terraform-ai', 'AI infrastructure as code', 'AI-powered assistance for writing and managing Terraform infrastructure configurations.', 'https://terraform.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Pulumi AI', 'pulumi-ai', 'AI-powered cloud infrastructure', 'Natural language to infrastructure as code using AI for cloud resource provisioning.', 'https://pulumi.com/ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Airplane', 'airplane', 'AI-powered internal tooling', 'Platform for building internal tools and workflows with AI-powered code generation and task automation.', 'https://airplane.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Convex', 'convex', 'AI-ready reactive backend', 'Reactive backend platform with built-in vector search, scheduling, and real-time sync for AI apps.', 'https://convex.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Prisma', 'prisma', 'AI-enhanced ORM', 'Next-generation ORM with AI-powered query optimization and schema management for Node.js and TypeScript.', 'https://prisma.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Drizzle', 'drizzle-orm', 'TypeScript ORM with AI features', 'Lightweight TypeScript ORM with SQL-like syntax and AI-powered migration generation.', 'https://orm.drizzle.team', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Playwright', 'playwright', 'AI-powered E2E testing', 'End-to-end testing framework with AI-powered test generation and auto-healing locators.', 'https://playwright.dev', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Stainless', 'stainless', 'AI SDK generation', 'Automatically generate typed SDKs from your API spec using AI for any programming language.', 'https://stainlessapi.com', 'paid', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Zod', 'zod', 'TypeScript schema validation', 'TypeScript-first schema validation with static type inference, widely used in AI application pipelines.', 'https://zod.dev', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('tRPC', 'trpc', 'End-to-end typesafe APIs', 'Framework for building typesafe APIs without schemas or code generation, popular in AI app stacks.', 'https://trpc.io', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Bun', 'bun', 'Fast JavaScript runtime', 'All-in-one JavaScript runtime and toolkit designed for speed with built-in bundler and test runner.', 'https://bun.sh', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Turborepo', 'turborepo', 'AI-optimized monorepo tool', 'High-performance monorepo build system with intelligent caching and task scheduling.', 'https://turbo.build', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Coolify', 'coolify', 'Self-hosted deployment platform', 'Open-source self-hosted alternative to Heroku/Netlify with one-click deployments and AI features.', 'https://coolify.io', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Fly.io', 'fly-io', 'Deploy app servers globally', 'Platform for running full-stack apps close to users with AI-powered scaling and edge computing.', 'https://fly.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Cloudflare Workers AI', 'cloudflare-workers-ai', 'AI inference at the edge', 'Run AI models on Cloudflares global network with serverless GPU inference at the edge.', 'https://developers.cloudflare.com/workers-ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('OpenRouter', 'openrouter', 'Unified AI model API', 'Single API to access hundreds of AI models from multiple providers with smart routing and fallbacks.', 'https://openrouter.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Replicate', 'replicate', 'Run AI models in the cloud', 'Platform for running open-source machine learning models in the cloud with a simple API.', 'https://replicate.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Together AI', 'together-ai', 'Fast open-source model inference', 'Platform for running and fine-tuning open-source AI models with fast inference and competitive pricing.', 'https://together.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Groq', 'groq', 'Ultra-fast LLM inference', 'LPU-powered inference engine delivering the fastest AI inference speeds for large language models.', 'https://groq.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Fireworks AI', 'fireworks-ai', 'Production AI model platform', 'Fastest and most efficient platform for running and fine-tuning generative AI models in production.', 'https://fireworks.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Anthropic API', 'anthropic-api', 'Claude API for developers', 'API access to Claude models for building AI-powered applications with advanced reasoning capabilities.', 'https://anthropic.com', 'paid', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('OpenAI API', 'openai-api', 'GPT and AI model APIs', 'API platform for accessing GPT, DALL-E, Whisper, and other AI models for building intelligent applications.', 'https://platform.openai.com', 'paid', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Google AI Studio', 'google-ai-studio', 'Build with Gemini models', 'Platform for prototyping and building with Google Gemini AI models with a simple web interface and API.', 'https://aistudio.google.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Mistral AI', 'mistral-ai', 'Open and portable AI models', 'Open-weight AI models and platform for building enterprise AI applications.', 'https://mistral.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Cohere', 'cohere', 'Enterprise AI platform', 'AI platform for enterprise search, generation, and classification with multilingual support.', 'https://cohere.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Modal', 'modal', 'Serverless AI infrastructure', 'Cloud platform for running AI workloads with serverless GPU compute and simple Python SDK.', 'https://modal.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Weights & Biases', 'wandb', 'ML experiment tracking', 'Platform for tracking ML experiments, visualizing results, and collaborating on AI projects.', 'https://wandb.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('MLflow', 'mlflow', 'Open-source ML lifecycle', 'Open-source platform for managing the end-to-end machine learning lifecycle.', 'https://mlflow.org', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Gradio', 'gradio', 'Build ML demos quickly', 'Python library for quickly creating customizable UI components for ML models and data science.', 'https://gradio.app', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Streamlit', 'streamlit', 'Data apps in Python', 'Open-source framework for building data and AI web applications entirely in Python.', 'https://streamlit.io', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('FastAPI', 'fastapi', 'Modern Python API framework', 'High-performance Python web framework ideal for building AI model serving endpoints.', 'https://fastapi.tiangolo.com', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Haystack', 'haystack', 'Open-source LLM framework', 'Open-source framework for building production-ready LLM applications with RAG pipelines.', 'https://haystack.deepset.ai', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('LlamaIndex', 'llamaindex', 'Data framework for LLMs', 'Data framework for ingesting, structuring, and accessing private data with large language models.', 'https://llamaindex.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('CrewAI', 'crewai', 'Multi-agent AI framework', 'Framework for orchestrating role-playing autonomous AI agents that collaborate to accomplish complex tasks.', 'https://crewai.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('AutoGen', 'autogen', 'Multi-agent conversations', 'Microsoft framework for building multi-agent conversational AI systems for complex workflows.', 'https://microsoft.github.io/autogen', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Semantic Kernel', 'semantic-kernel', 'AI orchestration SDK', 'Microsofts open-source SDK for integrating AI models into applications with plugins and planners.', 'https://learn.microsoft.com/semantic-kernel', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Vercel AI SDK', 'vercel-ai-sdk', 'TypeScript AI toolkit', 'TypeScript toolkit for building AI-powered applications with streaming, tool calling, and multi-model support.', 'https://sdk.vercel.ai', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Upstash', 'upstash', 'Serverless data for AI', 'Serverless Redis, Kafka, and vector database optimized for AI applications at the edge.', 'https://upstash.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Qdrant', 'qdrant', 'Vector similarity search engine', 'Open-source vector database for building AI applications with advanced filtering and hybrid search.', 'https://qdrant.tech', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Milvus', 'milvus', 'Open-source vector database', 'Cloud-native vector database for scalable similarity search and AI applications.', 'https://milvus.io', 'free', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Langfuse', 'langfuse', 'LLM observability platform', 'Open-source observability and analytics for LLM applications with tracing, evaluation, and prompt management.', 'https://langfuse.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Helicone', 'helicone', 'LLM monitoring and analytics', 'Open-source platform for monitoring, debugging, and optimizing LLM API usage and costs.', 'https://helicone.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('BrowserBase', 'browserbase', 'Headless browser for AI', 'Cloud browser infrastructure for AI agents to interact with web pages reliably.', 'https://browserbase.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, true),
('E2B', 'e2b', 'Code interpreter for AI', 'Cloud sandboxes for AI agents and apps to execute code safely in isolated environments.', 'https://e2b.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Val Town', 'val-town', 'Social coding platform', 'Platform for writing, running, and deploying small programs (vals) with AI assistance in the cloud.', 'https://val.town', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Stackblitz', 'stackblitz', 'AI-powered web IDE', 'Browser-based IDE powered by WebContainers with AI coding assistance for instant full-stack development.', 'https://stackblitz.com', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('CodeSandbox', 'codesandbox', 'Cloud development environment', 'Cloud IDE with AI-powered code completion and instant environment setup for web development.', 'https://codesandbox.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('GitPod', 'gitpod', 'Cloud development environments', 'Automated, AI-ready cloud development environments that spin up fresh for every task.', 'https://gitpod.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Codespaces', 'codespaces', 'GitHub cloud IDE', 'Full-featured cloud development environments in GitHub with AI Copilot integration.', 'https://github.com/features/codespaces', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('Graphite', 'graphite', 'AI code review platform', 'Modern code review platform with AI-powered review summaries and stacked pull request management.', 'https://graphite.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false),
('What The Diff', 'what-the-diff', 'AI pull request reviewer', 'AI-powered tool that reviews pull requests, generates summaries, and suggests improvements.', 'https://whatthediff.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('CodeRabbit', 'coderabbit', 'AI code review assistant', 'AI-powered code review tool that provides line-by-line suggestions on pull requests.', 'https://coderabbit.ai', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, true),
('Stenography', 'stenography', 'AI code documentation', 'AI tool that automatically generates documentation for code changes and functions.', 'https://stenography.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Swimm', 'swimm', 'AI code documentation', 'AI-powered tool for creating and maintaining code documentation that stays up to date with code changes.', 'https://swimm.io', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', false, false),
('Jam', 'jam-dev', 'AI bug reporting', 'One-click bug reporting tool with AI-powered debugging that captures console logs, network, and more.', 'https://jam.dev', 'freemium', '0a9f1cbe-1b2e-4b50-86df-de52cb0b0e03', true, false)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- STEP 2: Link ALL relevant tools to the Developer role
-- ============================================================

INSERT INTO public.tool_roles (tool_id, role_id)
SELECT t.id, '58072c5f-5ad0-4518-b4ec-87a8ceb83da0'
FROM public.tools t
WHERE t.slug IN (
  -- Existing tools
  'chatgpt', 'claude', 'gemini', 'perplexity', 'poe',
  'github-copilot', 'cursor', 'bolt', 'replit', 'v0',
  'windsurf', 'codeium', 'tabnine', 'notion-workspace',
  -- New tools
  'devin', 'sourcegraph-cody', 'amazon-codewhisperer', 'pieces',
  'askcodi', 'blackbox-ai', 'codiga', 'mutable-ai', 'mintlify',
  'sweep-ai', 'aider', 'continue-dev', 'supermaven', 'codium-ai',
  'snyk', 'sonarqube', 'qodo', 'vercel', 'railway', 'render',
  'hugging-face', 'langchain', 'ollama', 'lm-studio', 'phind',
  'warp', 'fig', 'gitlab-duo', 'jetbrains-ai', 'cline',
  'openhands', 'lovable', 'dify', 'n8n', 'retool',
  'supabase', 'planetscale', 'neon', 'pinecone', 'weaviate',
  'chromadb', 'sentry', 'datadog', 'posthog', 'raycast',
  'docker-ai', 'terraform-ai', 'pulumi-ai', 'airplane', 'convex',
  'prisma', 'drizzle-orm', 'playwright', 'stainless', 'zod',
  'trpc', 'bun', 'turborepo', 'coolify', 'fly-io',
  'cloudflare-workers-ai', 'openrouter', 'replicate', 'together-ai',
  'groq', 'fireworks-ai', 'anthropic-api', 'openai-api',
  'google-ai-studio', 'mistral-ai', 'cohere', 'modal', 'wandb',
  'mlflow', 'gradio', 'streamlit', 'fastapi', 'haystack',
  'llamaindex', 'crewai', 'autogen', 'semantic-kernel',
  'vercel-ai-sdk', 'upstash', 'qdrant', 'milvus', 'langfuse',
  'helicone', 'browserbase', 'e2b', 'val-town', 'stackblitz',
  'codesandbox', 'gitpod', 'codespaces', 'graphite',
  'what-the-diff', 'coderabbit', 'stenography', 'swimm', 'jam-dev'
)
ON CONFLICT DO NOTHING;
